export const useProducts = () => {
    return [
        {
            id: 1,
            name: 'Heavy Duty Steel Rebar',
            price: 120,
            rating: 4.7,
            reviews: 45,
            shortDescription: 'High-strength steel rebar for robust construction projects.',
            longDescription: 'Designed for maximum durability, this steel rebar ensures structural integrity in concrete frameworks.',
            sizes: ['12mm', '16mm', '20mm'],
            sku: 'RB001-HD',
            category: 'Rebar',
            tags: ['Steel', 'Construction', 'Durable', 'Structural'],
            imageUrl: 'https://onestopoutdoor.com/cdn/shop/files/Screenshot2023-10-31at12.16.05PM_5796b4c4-e855-4cf0-863c-27cd3f3e6bbf_x700.png?v=1738375550',
            stock: 50
        },
        {
            id: 2,
            name: 'Concrete Mixer 500L',
            price: 850,
            rating: 4.8,
            reviews: 28,
            shortDescription: 'Portable 500L concrete mixer for efficient mixing.',
            longDescription: 'Ideal for small to medium construction sites, this mixer ensures consistent concrete quality.',
            sizes: ['500L'],
            sku: 'CM001-500',
            category: 'Equipment',
            tags: ['Concrete', 'Mixer', 'Construction', 'Portable'],
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH7WWLdFtDORyrSDmk-66-Et9GVV-QUikxRg&s',
            stock: 10
        },
        {
            id: 3,
            name: 'Galvanized Steel Scaffolding',
            price: 200,
            rating: 4.6,
            reviews: 39,
            shortDescription: 'Sturdy scaffolding for safe construction work.',
            longDescription: 'Corrosion-resistant galvanized steel scaffolding for secure and reliable site access.',
            sizes: ['2m', '3m', '4m'],
            sku: 'SC001-GS',
            category: 'Scaffolding',
            tags: ['Scaffolding', 'Steel', 'Safety', 'Construction'],
            imageUrl: 'https://5.imimg.com/data5/RS/VJ/MY-38398126/3d-model-steel-scaffolding-500x500.jpg',
            stock: 30
        },
        {
            id: 4,
            name: 'Construction Safety Helmet',
            price: 25,
            rating: 4.9,
            reviews: 60,
            shortDescription: 'High-impact safety helmet for construction workers.',
            longDescription: 'Protects against falling objects with a comfortable fit for all-day use.',
            sizes: ['M', 'L'],
            sku: 'SH001-HI',
            category: 'Safety Gear',
            tags: ['Safety', 'Helmet', 'Construction', 'Protective'],
            imageUrl: 'https://i.ebayimg.com/images/g/MZAAAOSw0Dpkkq1F/s-l1200.jpg',
            stock: 100
        },
        {
            id: 5,
            name: 'Reinforced Concrete Blocks',
            price: 15,
            rating: 4.4,
            reviews: 25,
            shortDescription: 'Pre-cast concrete blocks for quick construction.',
            longDescription: 'High-quality reinforced blocks for walls and foundations, ensuring strength and stability.',
            sizes: ['20x20x40cm', '15x20x40cm'],
            sku: 'CB001-RC',
            category: 'Building Materials',
            tags: ['Concrete', 'Blocks', 'Construction', 'Foundation'],
            imageUrl: 'https://img.archiexpo.com/images_ae/photo-g/103640-12478590.jpg',
            stock: 200
        },
        {
            id: 6,
            name: 'Steel I-Beam',
            price: 300,
            rating: 4.8,
            reviews: 35,
            shortDescription: 'Heavy-duty steel I-beam for structural support.',
            longDescription: 'Engineered for high-load applications, perfect for large-scale construction projects.',
            sizes: ['3m', '6m', '9m'],
            sku: 'IB001-HD',
            category: 'Structural Steel',
            tags: ['Steel', 'I-Beam', 'Construction', 'Support'],
            imageUrl: 'https://yenaengineering.nl/wp-content/uploads/2022/05/image-18.png',
            stock: 25
        },
        {
            id: 7,
            name: 'Portable Welding Machine',
            price: 450,
            rating: 4.7,
            reviews: 42,
            shortDescription: 'Compact welding machine for on-site fabrication.',
            longDescription: 'Versatile and portable, ideal for welding steel components on construction sites.',
            sizes: ['One Size'],
            sku: 'WM001-P',
            category: 'Tools',
            tags: ['Welding', 'Portable', 'Construction', 'Steel'],
            imageUrl: 'https://5.imimg.com/data5/AP/HY/MY-4381880/portable-welding-machine.jpg',
            stock: 15
        },
        {
            id: 8,
            name: 'Construction Grade Plywood',
            price: 40,
            rating: 4.5,
            reviews: 30,
            shortDescription: 'Durable plywood for formwork and construction.',
            longDescription: 'High-strength plywood designed for concrete formwork and structural applications.',
            sizes: ['4x8ft', '3x6ft'],
            sku: 'PL001-CG',
            category: 'Building Materials',
            tags: ['Plywood', 'Construction', 'Formwork', 'Durable'],
            imageUrl: 'https://5.imimg.com/data5/TQ/XU/MY-34161188/commercial-plywood-500x500.jpg',
            stock: 80
        },
        {
            id: 9,
            name: 'High-Performance Concrete Pump',
            price: 1200,
            rating: 4.9,
            reviews: 20,
            shortDescription: 'Efficient concrete pump for large projects.',
            longDescription: 'Delivers high-volume concrete placement with precision and speed for major construction sites.',
            sizes: ['One Size'],
            sku: 'CP001-HP',
            category: 'Equipment',
            tags: ['Concrete', 'Pump', 'Construction', 'Heavy Duty'],
            imageUrl: 'https://image.made-in-china.com/2f0j00YRVovaHMskzh/High-Performance-Concrete-Machinery-Hbt10020V-100m3-H-7-4ton-Hydraulic-Trailer-Concrete-Pump-for-Sale.webp',
            stock: 5
        },
        {
            id: 10,
            name: 'Steel Reinforcement Mesh',
            price: 80,
            rating: 4.6,
            reviews: 38,
            shortDescription: 'Welded steel mesh for concrete reinforcement.',
            longDescription: 'Provides excellent tensile strength for slabs, walls, and foundations in construction.',
            sizes: ['2x4m', '3x6m'],
            sku: 'RM001-SM',
            category: 'Rebar',
            tags: ['Steel', 'Mesh', 'Construction', 'Reinforcement'],
            imageUrl: 'https://5.imimg.com/data5/SELLER/Default/2024/2/391484233/KA/VQ/XF/2905337/reinforcement-mesh.jpg',
            stock: 60
        },
        {
            id: 11,
            name: 'Cordless Power Drill',
            price: 150,
            rating: 4.7,
            reviews: 50,
            shortDescription: 'Versatile cordless drill for construction tasks.',
            longDescription: 'High-torque, battery-powered drill for drilling and fastening in various materials.',
            sizes: ['One Size'],
            sku: 'PD001-CD',
            category: 'Tools',
            tags: ['Drill', 'Cordless', 'Construction', 'Power Tool'],
            imageUrl: 'https://m.media-amazon.com/images/I/71ZHD9GLMTL._AC_SL1500_.jpg',
            stock: 40
        },
        {
            id: 12,
            name: 'Industrial Wheelbarrow',
            price: 90,
            rating: 4.5,
            reviews: 32,
            shortDescription: 'Heavy-duty wheelbarrow for material transport.',
            longDescription: 'Designed for rugged construction sites, with a large capacity for hauling debris and materials.',
            sizes: ['6 cu ft', '8 cu ft'],
            sku: 'WB001-HD',
            category: 'Equipment',
            tags: ['Wheelbarrow', 'Construction', 'Transport', 'Heavy Duty'],
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJBwWnJeOKJf0Mp8VoYYI6usx9yprICOMnSA&s',
            stock: 20
        },
        {
            id: 13,
            name: 'Safety Harness Kit',
            price: 70,
            rating: 4.8,
            reviews: 48,
            shortDescription: 'Full-body safety harness for high-altitude work.',
            longDescription: 'Ensures worker safety with adjustable straps and durable connectors for elevated tasks.',
            sizes: ['S/M', 'L/XL'],
            sku: 'SH002-HK',
            category: 'Safety Gear',
            tags: ['Safety', 'Harness', 'Construction', 'Height Safety'],
            imageUrl: 'https://m.media-amazon.com/images/I/81QgUXgRLtL._UY1000_.jpg',
            stock: 75
        },
        {
            id: 14,
            name: 'Concrete Vibrator',
            price: 250,
            rating: 4.6,
            reviews: 29,
            shortDescription: 'Portable vibrator for concrete consolidation.',
            longDescription: 'Ensures uniform concrete setting by removing air bubbles, ideal for foundations and slabs.',
            sizes: ['One Size'],
            sku: 'CV001-P',
            category: 'Tools',
            tags: ['Concrete', 'Vibrator', 'Construction', 'Compaction'],
            imageUrl: 'https://m.media-amazon.com/images/I/712VbuqP7zL.jpg',
            stock: 15
        },
        {
            id: 15,
            name: 'Steel Trowel Set',
            price: 35,
            rating: 4.4,
            reviews: 26,
            shortDescription: 'Durable trowel set for masonry work.',
            longDescription: 'High-quality steel trowels for smooth concrete and plaster finishing.',
            sizes: ['Small', 'Medium', 'Large'],
            sku: 'TR001-ST',
            category: 'Tools',
            tags: ['Trowel', 'Masonry', 'Construction', 'Finishing'],
            imageUrl: 'https://m.media-amazon.com/images/I/61gc361vQ6L._UF1000,1000_QL80_.jpg',
            stock: 60
        },
        {
            id: 16,
            name: 'Insulated Work Gloves',
            price: 20,
            rating: 4.7,
            reviews: 55,
            shortDescription: 'Protective gloves for construction tasks.',
            longDescription: 'Durable, insulated gloves offering grip and protection for handling rough materials.',
            sizes: ['M', 'L', 'XL'],
            sku: 'GL001-IW',
            category: 'Safety Gear',
            tags: ['Gloves', 'Safety', 'Construction', 'Protective'],
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8ztKs3sJtuD8Jced2cnfL5tqOW-I_k6Jc7g&s',
            stock: 120
        },
        {
            id: 17,
            name: 'Portable Generator 5000W',
            price: 600,
            rating: 4.8,
            reviews: 41,
            shortDescription: 'Powerful generator for construction sites.',
            longDescription: 'Reliable 5000W generator for powering tools and equipment in remote locations.',
            sizes: ['One Size'],
            sku: 'PG001-5K',
            category: 'Equipment',
            tags: ['Generator', 'Power', 'Construction', 'Portable'],
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRqO3UYRvWoMkQY3yURjFnGiLEW_xv3Mp5Uw&s',
            stock: 8
        },
        {
            id: 18,
            name: 'Cement Mixer Drum',
            price: 300,
            rating: 4.5,
            reviews: 33,
            shortDescription: 'Replacement drum for cement mixers.',
            longDescription: 'Heavy-duty steel drum compatible with standard cement mixers for efficient mixing.',
            sizes: ['400L', '600L'],
            sku: 'CD001-HD',
            category: 'Equipment',
            tags: ['Cement', 'Mixer', 'Construction', 'Drum'],
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAFha96eWnnFcuazUEt2pyhjMKfDuG8jkRQg&s',
            stock: 12
        },
        {
            id: 19,
            name: 'Steel Cable Winch',
            price: 180,
            rating: 4.6,
            reviews: 37,
            shortDescription: 'Heavy-duty winch for lifting materials.',
            longDescription: 'Robust steel cable winch for hoisting heavy construction materials safely.',
            sizes: ['One Size'],
            sku: 'CW001-HD',
            category: 'Tools',
            tags: ['Winch', 'Lifting', 'Construction', 'Steel'],
            imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTO1HAQ1mdX535aVQaqOErBUM3wTcfIQWb0Sg&s',
            stock: 25
        },
        {
            id: 20,
            name: 'Construction Barrier Fence',
            price: 50,
            rating: 4.4,
            reviews: 28,
            shortDescription: 'Durable fencing for site safety.',
            longDescription: 'High-visibility, weather-resistant barrier fencing for securing construction perimeters.',
            sizes: ['50m', '100m'],
            sku: 'BF001-HV',
            category: 'Safety Gear',
            tags: ['Fencing', 'Safety', 'Construction', 'Barrier'],
            imageUrl: 'https://www.jaybro.com.au/pub/Concrete Mixer 500Lmedia/mageplaza/blog/post/0/1/01-2700-edited.jpg',
            stock: 90
        }
    ]
}